FROM composer:latest as composer

FROM ubuntu:20.04 as final

ARG ARCH=linux-amd64

RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
    apt-transport-https \
    apt-utils \
    ca-certificates \
    curl \
    git \
    iputils-ping \
    jq \
    lsb-release \
    software-properties-common \
    zip \
    unzip \
    software-properties-common

RUN DEBIAN_FRONTEND=noninteractive apt update

RUN DEBIAN_FRONTEND=noninteractive apt install -y php7.4 \
    php7.4-mysql \
    php7.4-curl \
    php7.4-zip \
    php7.4-bcmath \
    php7.4-fpm \
    php7.4-mbstring \
    php7.4-common \
    php7.4-xml \
    php7.4-redis

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

ENV TARGETARCH=${ARCH}

WORKDIR /azp
VOLUME /opt

COPY ../start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]
